// <auto-generated />
using System;
using DataProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataProject.Migrations
{
    [DbContext(typeof(DataProjectDbContext))]
    partial class DataProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataProject.Models.Criminal", b =>
                {
                    b.Property<int>("CriminalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriminalId"));

                    b.Property<string>("CriminalDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CriminalHistory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CriminalPictureUrl")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LastKnownLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("CriminalId");

                    b.ToTable("Criminals");

                    b.HasData(
                        new
                        {
                            CriminalId = 1,
                            CriminalDescription = "Known for cybercrimes and fraud.",
                            CriminalHistory = "Arrested twice for Sexual offences.",
                            CriminalPictureUrl = "https://images.unsplash.com/photo-1589304099692-7c72d558c2f3?q=80&w=1976&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            DateOfBirth = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Larsen",
                            Gender = "Male",
                            LastKnownLocation = "Oslo, Norway",
                            LastName = "Jack",
                            Nationality = "American",
                            NickName = "Johnny"
                        },
                        new
                        {
                            CriminalId = 2,
                            CriminalDescription = "Specializes in high-profile thefts.",
                            CriminalHistory = "Involved in Drug and alcohol offences.",
                            CriminalPictureUrl = "https://images.unsplash.com/photo-1682965636797-e97babe032b7?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            DateOfBirth = new DateTime(1990, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Røger",
                            Gender = "Male",
                            LastKnownLocation = "Los Angeles",
                            LastName = "Hanna",
                            Nationality = "Canadian",
                            NickName = "The Phantom"
                        },
                        new
                        {
                            CriminalId = 3,
                            CriminalDescription = "Specializes in high-profile thefts.",
                            CriminalHistory = "Involved in offences for profit.",
                            CriminalPictureUrl = "https://images.unsplash.com/photo-1603198565875-f53d90dc8004?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            DateOfBirth = new DateTime(1990, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Dhani",
                            Gender = "Female",
                            LastKnownLocation = "Mumbai, maharashtra, india",
                            LastName = "Dhal",
                            Nationality = "Canadian",
                            NickName = "The Phantom"
                        });
                });

            modelBuilder.Entity("DataProject.Models.OffenceVictim", b =>
                {
                    b.Property<int>("OffencesId")
                        .HasColumnType("int");

                    b.Property<int>("VictimId")
                        .HasColumnType("int");

                    b.Property<int?>("CriminalId")
                        .HasColumnType("int");

                    b.HasKey("OffencesId", "VictimId");

                    b.HasIndex("CriminalId");

                    b.HasIndex("VictimId");

                    b.ToTable("OffenceVictims");

                    b.HasData(
                        new
                        {
                            OffencesId = 1,
                            VictimId = 2
                        },
                        new
                        {
                            OffencesId = 2,
                            VictimId = 1
                        },
                        new
                        {
                            OffencesId = 2,
                            VictimId = 3
                        });
                });

            modelBuilder.Entity("DataProjectDb.Models.Victim", b =>
                {
                    b.Property<int>("VictimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VictimId"));

                    b.Property<string>("VictimsLocation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VictimsName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VictimId");

                    b.ToTable("Victims");

                    b.HasData(
                        new
                        {
                            VictimId = 1,
                            VictimsLocation = "Brooklyn, NYC",
                            VictimsName = "Linda Park",
                            Year = 2023
                        },
                        new
                        {
                            VictimId = 2,
                            VictimsLocation = "Manhattan, NYC",
                            VictimsName = "Robert Thompson",
                            Year = 2022
                        },
                        new
                        {
                            VictimId = 3,
                            VictimsLocation = "Brooklyn, NYC",
                            VictimsName = "Linda Park",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Offence", b =>
                {
                    b.Property<int>("OffencesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OffencesId"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("CriminalId")
                        .HasColumnType("int");

                    b.Property<string>("OffenceName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("OffencesId");

                    b.HasIndex("CriminalId");

                    b.ToTable("Offences");

                    b.HasData(
                        new
                        {
                            OffencesId = 1,
                            Count = 7484,
                            CriminalId = 1,
                            OffenceName = "Sexual offences",
                            Year = 2023
                        },
                        new
                        {
                            OffencesId = 2,
                            Count = 29788,
                            CriminalId = 2,
                            OffenceName = "Drug and alcohol offences",
                            Year = 2022
                        },
                        new
                        {
                            OffencesId = 3,
                            Count = 42994,
                            CriminalId = 1,
                            OffenceName = "Violence and maltreatment",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("DataProject.Models.OffenceVictim", b =>
                {
                    b.HasOne("DataProject.Models.Criminal", null)
                        .WithMany("OffenceVictims")
                        .HasForeignKey("CriminalId");

                    b.HasOne("Offence", "Offence")
                        .WithMany("OffenceVictims")
                        .HasForeignKey("OffencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataProjectDb.Models.Victim", "Victim")
                        .WithMany("OffenceVictims")
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offence");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("Offence", b =>
                {
                    b.HasOne("DataProject.Models.Criminal", "Criminal")
                        .WithMany("Offences")
                        .HasForeignKey("CriminalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criminal");
                });

            modelBuilder.Entity("DataProject.Models.Criminal", b =>
                {
                    b.Navigation("OffenceVictims");

                    b.Navigation("Offences");
                });

            modelBuilder.Entity("DataProjectDb.Models.Victim", b =>
                {
                    b.Navigation("OffenceVictims");
                });

            modelBuilder.Entity("Offence", b =>
                {
                    b.Navigation("OffenceVictims");
                });
#pragma warning restore 612, 618
        }
    }
}
